on:  
  workflow_run:
    workflows: [Determin Env]
    types:
      - completed

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: "Check code"
      uses: 'actions/checkout@v1'
    - name: "Print status"
      run: echo "This is job2"