name: Determin Env

on :
    release:
      types: [published]
jobs:
    Environment:
      runs-on: ubuntu-latest
      outputs:
        ENVIRONMENT: ${{ steps.define_environment.outputs.ENVIRONMENT }}
      steps:
      - id: define_environment
        run: echo "ENVIRONMENT=$(echo $GITHUB_REF | cut -d'/' -f 3 | awk -F '-' '{print $1}')" >> $GITHUB_OUTPUT
    SetJob1:
        needs: [Environment]
        runs-on: ubuntu-latest
        if: ${{  needs.Environment.outputs.ENVIRONMENT == 'prod' }}
        steps:
            echo "This is production"
#          - name: Trigger production workflow
#            uses: actions/trigger-workflow@v2
#            with:
#              workflow: job1.yaml

          - name: Trigger stage workflow
            uses: ./.github/workflow/job1.yaml




   



  